import { Option } from '~/components/Select';

export const difficultyOptions: Option<number>[] = [
  { label: '1', value: 1 },
  { label: '2', value: 2 },
  { label: '3', value: 3 },
  { label: '4', value: 4 },
  { label: '5', value: 5 },
];

export const categoryOptions: Option<number>[] = [
  { label: '歴史', value: 1 },
  { label: '文学', value: 2 },
  { label: '芸術', value: 3 },
  { label: '文化', value: 4 },
  { label: '言葉', value: 5 },
  { label: '地理', value: 6 },
  { label: '政治経済', value: 7 },
  { label: '公民', value: 8 },
  { label: '物理・化学', value: 9 },
  { label: '天文・気象', value: 10 },
  { label: '生物・医学', value: 11 },
  { label: '数学・情報', value: 12 },
  { label: 'スポーツ', value: 13 },
  { label: 'ライフスタイル', value: 14 },
  { label: '芸能', value: 15 },
  { label: '古典芸能', value: 16 },
  { label: 'ホビー・ゲーム', value: 17 },
  { label: '漫画・アニメ', value: 18 },
  { label: 'ノンセクション', value: 19 },
];

export const subCategoryOptions: Option<number>[] = [
  { label: '日本史', value: 1 },
  { label: '世界史', value: 2 },
  { label: '日本文学', value: 3 },
  { label: '外国文学', value: 4 },
  { label: 'クラシック音楽', value: 5 },
  { label: '美術', value: 6 },
  { label: '神話', value: 7 },
  { label: '宗教・文化', value: 8 },
  { label: '日本語', value: 9 },
  { label: '漢字・熟語', value: 10 },
  { label: '外国語', value: 11 },
  { label: '日本地理', value: 12 },
  { label: '世界地理', value: 13 },
  { label: '政治', value: 14 },
  { label: '経済・産業', value: 15 },
  { label: '現代社会', value: 16 },
  { label: '哲学', value: 17 },
  { label: '物理', value: 18 },
  { label: '化学', value: 19 },
  { label: '天文', value: 20 },
  { label: '気象', value: 21 },
  { label: '地学', value: 22 },
  { label: '生物', value: 23 },
  { label: '医学', value: 24 },
  { label: '数学', value: 25 },
  { label: '情報技術', value: 26 },
  { label: '球技', value: 27 },
  { label: '団体競技(球技以外)', value: 28 },
  { label: '格闘技・武道', value: 29 },
  { label: '陸上・レース', value: 30 },
  { label: 'スポーツその他', value: 31 },
  { label: 'グルメ', value: 32 },
  { label: 'ファッション', value: 33 },
  { label: '生活', value: 34 },
  { label: '現代芸能', value: 35 },
  { label: '音楽(クラシック以外)', value: 36 },
  { label: '古典芸能', value: 37 },
  { label: '唱歌・民謡', value: 38 },
  { label: 'ホビー', value: 39 },
  { label: 'デジタルゲーム', value: 40 },
  { label: '漫画・アニメ', value: 41 },
  { label: 'ノンセクション', value: 42 },
];

export const questionsNumberOptions: Option<number>[] = [
  { label: '10', value: 10 },
  { label: '30', value: 30 },
  { label: '50', value: 50 },
  { label: '100', value: 100 },
  { label: '200', value: 200 },
];
